name: Flutter CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: flutter action
      uses: subosito/flutter-action@v1.1.1
    - name: flutter pub get
      run: flutter pub get
    - name: Flutter test
      run: flutter test
    - name: flutter build apk
      run: flutter build apk
