name: Flutter CD

on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
    - name: Flutter pub get
      run: flutter pub get
    - name: Flutter test
      run: flutter test
    - name: Flutter build apk
      run: flutter build apk
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
